services:
  spring-boot-3-keycloak:
    image: spring-boot-3-keycloak:1.0
    networks:
      - keycloak-network
    container_name: spring-boot-3-keycloak
    environment:
      - KEYCLOAK_HOST=keycloak:8080
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    networks:
      - keycloak-network
    image: quay.io/keycloak/keycloak:26.3
    container_name: standalone-keycloak
    command: start-dev
    environment:
      # Database Settings
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=123456

      # Admin Credentials
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

      # Enable Health and Metrics
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true

      # KC explicit settings
      - KC_HOSTNAME=keycloak
    ports:
      - "8080:8080"
      - "9000:9000" # Note: Port 9000 is often for Keycloak's internal/management interface, keeping it can be useful.
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { java.net.URI uri = java.net.URI.create(args[0]); System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)uri.toURL().openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s

  postgresql:
    networks:
      - keycloak-network
    image: 'postgres:17.5-alpine'
    container_name: keycloak-postgresql
    volumes:
      - keycloak-postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  keycloak-postgres-volume:
    name: keycloak-postgres-volume

networks:
  keycloak-network:
    driver: bridge